### ISSUE TITLE
Why not Dhall?

### ISSUE THREAD

**Issue by jjant** [apple/pkl#119]
I did read your [comparison](https://github.com/apple/pkl/blob/db55c527c651643649cf55acda6ef5c143d0a664/docs/modules/introduction/pages/comparison.adoc#pkl-vs-other-config-languages), but I still don't understand why you guys needed to create a new language, it sounds like if ease of use within the JVM is primarily what drove this, you could've made a JVM-based toolchain for Dhall instead.

**Comment by sondr3** [comment]
I have used Dhall quite a bit and like the idea of it much more than the actual experience of using it. It's also very alien for developers who do not come from a functional background and requires much more investment to understand how it works or how to use it well. Dhall is also only maintained as a Haskell package, both the Rust and Java bindings are unmaintained whereas Pkl comes out the gate swinging with JVM/Go/Swift support. I adore the idea behind Dhall, but would not recommend it to anyone except FP people who use Haskell or to experiment with a total programming language.

**Comment by holzensp** [comment]
I come from a Haskell background, so I really appreciate Dhall, but I've also learned that _a lot_ of people don't have/want that functional perspective. Dhall wasn't where it is today when development on Pkl started _and_ Pkl focussed on meeting its users where they are.

I'm closing this _Issue_, because the question doesn't allow for a definition of "done," but if you feel your question isn't yet answered to satisfaction, feel free to open a Discussion thread.
