### ISSUE TITLE
Functions are not inherited by amending modules

### ISSUE THREAD

**Issue by philippemerle** [apple/pkl#288]
The language reference says that a module amending another module inherits from all the members of the amended module. But functions of the amended module seem to be not inherited from as shown in the following example.

File `base_template.pkl`
```
persons: Listing<Person>
class Person {
  name: String
}
function buildPerson(val: String): Person = new {
  name = val
}
```

File `my_template.pkl`
```
amends "base_template.pkl"

persons {
  new Person { name = "Me"}
  buildPerson("you")
}
```

Evaluating `my_template.pkl` produces the following error
```
–– Pkl Error ––
Cannot find method `buildPerson`.

5 | buildPerson("you")
    ^^^^^^^^^^^^^^^^^^
at my_template#persons[#2] (file:///.../my_template.pkl, line 5)

3 | persons {
    ^^^^^^^^^
at my_template#persons (file:///.../my_template.pkl, line 3)

106 | text = renderer.renderDocument(value)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at pkl.base#Module.output.text (https://github.com/apple/pkl/blob/0.25.2/stdlib/base.pkl#L106)
```

Do I miss something?

**Comment by stackoverflow** [comment]
Scoping rules in Pkl can be a bit tricky. You can use `module` to reference top level variables and functions:

```
amends "base_template.pkl"

persons {
  new Person { name = "Me"}
  module.buildPerson("you")
}
```

**Comment by philippemerle** [comment]
Thank you the provided solution. But this will be simpler if inherited functions could be called directly without prefixing them by `module.`. Perhaps in a future pkl release?

**Comment by bioball** [comment]
The scoping rules in place here provide an important safety net; that the resolved member can't change by adding something else in the (grand)parent module.

Without this rule, it would be possible to change what a variable/method resolved to by changing something in the base module. It would make it so that adding names to a module might produce very unexpected results in the generated configuration.

For example, if this worked:

parent.pkl
```
function foo() = "bar"

class MyObject {
  prop: String
}

obj: MyObject
```

child.pkl
```
obj {
  prop = foo()
}
```

Then, a new `function foo()` was introduced:

```diff
 function foo() = "bar"

 class MyObject {
   prop: String
+
+  function foo() = "baz"
 }
 
 obj: MyObject
```

This change seems innocent when just looking at `parent.pkl`, but it would change `foo()` within `child.pkl` to resolve to a _different_ method. This behavior would make it too easy for authors to break their own code in hidden ways.

**Comment by bioball** [comment]
Closing as not planned, as this works as-intended.
