### ISSUE TITLE
Wrong result of unary `-` operation

### ISSUE THREAD

**Issue by taichi-ishitani** [apple/pkl#650]
Pkl will return the wrong result for the unary `-` operation like below.

```pkl
// foo.pkl
a = --1
```

The result of this operation should be `1` but got `-1`.

![image](https://github.com/user-attachments/assets/4e2583eb-db52-4756-80ac-b1de87ec5fe2)

**Comment by bioball** [comment]
Thanks for the report; definitely looks like bug. Haven't looked into it yet, but this looks parser related. Unary minus otherwise works as expected:

```pkl
negativeOne = -1
a  = -negativeOne
```

Produces:

```
negativeOne = -1
a = 1
```

**Comment by DFrenkel** [comment]
Double unary minus could be easily confused with a prefix decrement.

Java, JavaScript, Golang, .NET  all fail to compile `--1` expression either expecting parentheses around `(-1)` or expecting a variable to be decremented instead of a literal. 
Increment/decrement `++` and `--` are deprecated in Swift 2.2 and removed in Swift 3.
Python, however, handles `x = --1` correctly.

I _think_  pkl should follow the simplest solution and expect `++a` or `--a` to fail with a clear message . 
An alternative is to start support prefix (_and postfix for symmetry?_) increments and decrements:

- Expect `--a` to fail when `a` is numerical literal 
- Expect `--a` to act as a standard _prefix decrement_ when `a` is a variable

What do you think?

**Comment by HT154** [comment]
This bug extends through parentheses as well:
```
x = -(-1)
// x = -1
```

A decrement operator of any kind seems like the wrong choice for Pkl as it implies some form of imperative mutation that doesn't exist in the language.

**Comment by bioball** [comment]
Good point, @DFrenkel. I'm sympathetic to the idea that `--a` should hard-fail, because it might be confused with decrement.
