### ISSUE TITLE
Pkl ignores format when evaluating expressions

### ISSUE THREAD

**Issue by pauloborges** [apple/pkl#742]
Example file:

```
cat file.pkl
field {
    key = "value"
}
```

Evaluating the whole file works as expected:

```
pkl eval -f yaml file.pkl
field:
  key: value
```

But evaluating an expression ignores the format argument:

```
pkl eval -f yaml -x field file.pkl
new Dynamic { key = "value" }
```

**Comment by HT154** [comment]
This is currently expected behavior and not a bug, but this is definitely a valid feature request. You can emulate this using `-x 'module.renderer.renderValue(<expr>)`.

You can see how the output format selection is implemented here, which might help explain what's happening here: https://github.com/apple/pkl/blob/466ae6fd4c72aa7ccabde970131eccbc2a690b12/stdlib/base.pkl#L93-L107

**Comment by ThinkChaos** [comment]
The workaround above doesn't work, it should be `-x 'module.output.renderer.renderValue(<expr>)`
